### ISSUE TITLE
A failing existence check does not return a diagnostic message

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#100]
If you run an existence check for a file, it seems as though it does not produce any debugging output when the check fails. For instance, please consider this output:

```
✘  The file travels_submission.png exists in the images directory
   ➔
```

Note that the check fails because the file does not exist in the specified directory. However, there is no debugging output next to the arrow to indicate why the check failed. While there is not a lot of debugging information that we can provide in this situation, we should try to provide some output, I suggest.

**Comment by gkapfham** [comment]
Hello @corlettim and @alexheinle and @Michionlion and Hannah (when she is in the organization!), I suggest that we consider working on determining if this is a bug and then fixing it as part of the group study this semester. What do you think? Please respond here and then let us also plan to meet for further discussion.

Some quick points:

* We need to see if we can reproduce this in sample project beyond my own
* We need to write a failing test case to support our bug fixing
* We need to decide if it is possible to implement a good fix and, if yes, the go ahead and start

My intuition is that it will be possible to resolve this issue. What do you think?

**Comment by Michionlion** [comment]
I can attest to seeing this in other examples before -- specifically some of the Web Development labs. I think this would be a good start!

We should figure out a good meeting time for all of the participants, and attempt to hold meetings every week to two weeks.

**Comment by gkapfham** [comment]
Hi @alexheinle and @corlettim and @schultzh and @Michionlion, okay, let's focus here first. I think that the first critical task is to find out which part of the system is running the check and then not producing the correct diagnostic information. Once we discover this, we can start to think about a fix. Please report back here once you have discovered more information. Also, can all of us talk during the CMPSC 302 laboratory session on Monday of next week so that we can find a time for a regular meeting?

I should note that there are also some other issues that we can tackle, like those that focus on documentation, so that we can practice working on the GitHub Flow model. Then, we might be better prepared to work on this issue using GitHub Flow.

**Comment by Michionlion** [comment]
I'm closing this as PR #118 was merged.
