### ISSUE TITLE
No CONTRIBUTING.md or CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Alex-Yarkosky** [GatorEducator/gatorgrader#131]
In order to improve the state of this project as an open source one, these proposed files should be included to make it easier to contribute in a productive way in accordance with the need outlined [here](https://opensource.guide/). I suggest that the Code of Conduct be taken from [here](https://www.contributor-covenant.org/) to avoid having to create one from scratch. GitHub also has some suggestions for making a Contributing file that can be found [here](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors). These files are also suggested on the [Community](https://github.com/GatorEducator/gatorgrader/community) page.

**Comment by Alex-Yarkosky** [comment]
Also, [here](https://github.com/AVMf/avmf/blob/gradle/CONTRIBUTING.md) is a `CONTRIBUTING.md` file that I made for another project, AVM*f*

**Comment by gkapfham** [comment]
Thanks for opening this issue and sharing these examples, @Alex-Yarkosky. I will work on this task in the next few weeks. If you have time and are interested in doing so, you are also warmly invited to work on this task.

**Comment by gkapfham** [comment]
Hi @Alex-Yarkosky, this issue is resolved by PR #181.
