### ISSUE TITLE
Delete Java Code and Re-Write Tests to Generate This Input

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#135]
Right now GatorGrader includes a Java source code program inside of its repository, which is not ideal. The test cases should be re-written so that they create this file in an internal, in-test directory that is only available during testing. This will then ensure that the main GatorGrader repository does not contain Java source code inside of it!

**Comment by gkapfham** [comment]
It is worth noting that this is not _exclusively_ related to testing GatorGrader. The sample program is also used as an example in the README file. However, I suggest that @schultzh and @corlettim and I rewrite this part of the documentation to instead refer to a file that exists inside of the GatorGrader distribution, say, for instance, the main `gatorgrader.py` file.

**Comment by schultzh** [comment]
Where is the java source code located? Should the new tests be written before the source code is deleted?

**Comment by gkapfham** [comment]
Hi @schultzh, thanks for this question. I think that the `internal` directory was previously only used by a run of the program as described in the `README.md` file. I do not see any examples where it is now used in the test suite. As such, I think that you can safely create a branch to delete this directory.

**Comment by schultzh** [comment]
Okay great!! I'll work on that today/tomorrow.

**Comment by gkapfham** [comment]
Great, thanks @schultzh, your help is greatly appreciated!

**Comment by gkapfham** [comment]
Hi @schultzh I have removed the "help-wanted" tag for this issue under the view that you will create a branch and a PR that removes the code that is no longer needed. Let me know if this decision is not acceptable to you. Thanks!

**Comment by schultzh** [comment]
@gkapfham I apologize for not getting to this issue when I planned to, I am currently writing a research paper and full-time at work. After this week I will have much more time to put into helping with these fixes!!

**Comment by gkapfham** [comment]
Hi @schultzh, no problem at all! Since I am going to be away all week next week, I have been scrambling to finish a bunch of issues on this project. I have an open PR #173 that should resolve this issue. If you have time, please check to make sure that I have not broken anything! Thanks!
