### ISSUE TITLE
Add SVG of the Logo to the Hidden GitHub Directory

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#136]
Now that we have a new logo, it would be a good idea if we could also store the SVG file. This would make it easier for us to manipulate the logo or to leverage its high quality as a starting point for other logos. I suggest that we store this logo in the `.github` directory. Does that seem okay @dubswalker and @Michionlion?

**Comment by Michionlion** [comment]
As long as we continue to use the `png`, which is needed for firefox compatibility, when displaying the logo, I think that would work.

**Comment by gkapfham** [comment]
Yes, @Michionlion I agree that we should use the PNG file. With that said, I would like to keep the SVG file so that we can modify the logo if, for instance, we want a smaller version to print on a sticker.
