### ISSUE TITLE
Add all contributors feature to README file 

### ISSUE THREAD

**Issue by schultzh** [GatorEducator/gatorgrader#150]
Replace current contributors section in current `README.md` file to pull contributors information from their GitHub accounts.

**Comment by schultzh** [comment]
@gkapfham @Michionlion @corlettim @alexheinle 
I've done some more research on the All Contributors feature. There are two ways to implement this feature.
1) Install from NPM as a dependency 
2) using the all contributors bot 

From what I can tell, using the bot involves more maintenance on our end, needing someone to call the bot and the contributor you want to add to the table, where the CLI maintains the table automatically. 

Thoughts on which way is better for us/how the code is set up?

**Comment by Michionlion** [comment]
I think the bot will probably be better; I want to both avoid extra dependencies within our own code, and enable better control. It seems the bot should be able to do that -- manually specifying contributors is probably a good idea, because then control can be easily exercised over that list.

**Comment by schultzh** [comment]
Okay! I will have more details for our meeting on Wednesday.

**Comment by gkapfham** [comment]
Thanks for investigating this issue @schultzh. I agree with the point raised by @Michionlion. Overall, we probably want to adopt the automated approach. But, there may be some cases in which we need to manually designate someone as a contributor --- like in the case when someone designs a logo and there is not an easy way for the bot to notice this. Okay, looking forward to your report later today!
