### ISSUE TITLE
Provide a Linting Interface Instead of a Composable Interface

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#175]
**Is your feature request related to a problem? Please describe.**

Right now, GatorGrader supports the specification of a check, on say a file or the output of a command, through a "composable" interface where it is possible to mix-and-match command-line arguments. While this approach supports flexibility and it allows educators to specify unique checks, it is difficult to start with the check specification task and to know what checks are available. Overall, I'm no longer convinced that this is the best interface for GatorGrader. 

**Describe the solution you'd like**

I think that it would be better if GatorGrader instead supported a "linting interface" where, broadly, you would specify:

1. The name of the check that you want to perform
2. Arguments (or, keyword arguments) specifically pertaining to this check

For instance:

`FileExists Directory=<directory name> File=<filename>`

**Describe alternatives you've considered**

It is worth thinking about whether the arguments to a linting check should be positional or keyword-based. Currently, I am leaning towards implementing them in a keyword-based fashion because this provides some flexibility and it also is more self-documenting. What do you think?

To implement this, we should think carefully about how `argparse` supports sub-arguments and a simpler form of argument verification. Right now, argument verification is very difficult because of the fact that you can mix-and-match the command-line arguments in various ways. I want to make sure that the new linting approach makes argument verification much easier.

**Additional context**

So, @corlettim and @schultzh and @alexheinle and @Michionlion can you give some ideas about what you would prefer in the linting interface? Also, can you give some examples of a command expressed in the current "composable" interface and then what it would look like in the new "linting" interface?

Finally, I'm inclined to deprecate the old interface, meaning that all of the old assignments will stop working once we implement the new approach. If @jjumadinova has concerns about this issue, I hope that she can share them in this issue as well.

**Comment by gkapfham** [comment]
Also, @Michionlion and @corlettim and @schultzh we should start to think about whether we want to also adopt a plugin framework approach when we introduce the linting interface. Any ideas on this step?

**Comment by corlettim** [comment]
> Also, @Michionlion and @corlettim and @schultzh we should start to think about whether we want to also adopt a plugin framework approach when we introduce the linting interface. Any ideas on this step?

@gkapfham Just so I have a better understanding and can hopefully provide ideas...what exactly would the plugin framework approach (if used/adopted) accomplish? Would it allow users to access Gator Grader more easily? Sorry if I am completely misunderstanding but I just wanted to clarify :)

**Comment by gkapfham** [comment]
Hi @corlettim thanks for your question. The idea of providing a plug interface is that it would allow instructors to add new checks to GatorGrader without having to understand any of the internals of its implementation.

Right now, GatorGrader is "batteries included" since it allows developers to specify checks for a project by "mixing and matching" the existing checks. But, it is not currently extensible. Adding new checks to GatorGrader is difficult.

With that said, I have *a lot* of questions about how a developer might add their own checks. @corlettim and @Michionlion one of the big issues is where these new plugins that provide checks will "live"? Do they come in a Git repository? Do we then have GatorGrader read in plugins from a "non-application directory"?

**Comment by schultzh** [comment]
I also feel the linting approach would be better than the current composable system. 

Is it possible to create a file that holds all the possible keywords and arguments that could be accessible to all who use it?  Potentially a Github repo?

**Comment by Michionlion** [comment]
I think the simplest way to implement a plugin interface would be to specify the python file the check is in inside the call to GatorGrader, something like `python gatorgrader.py --plugin /home/saejin/gg/plugin.py FileExists Directory=<directory name> File=<filename>`

**Comment by corlettim** [comment]
I definitely think that the plugin would be a great feature to have with the new linting approach because it would not only allow for flexibility with the style of checks but make it so that each user/instructor/professor can make the tool their own. If the plugins for the personalized checks would go into a visible file/directory, this could also open up a great opportunity for other users/instructors/professors to see how others are going about their courses and expand upon their own. Consequently, I think the plugin feature is definitely something that can be added in with the linting approach but should not take the main focus since we want to get away from the composable system sooner rather than later.

**Comment by gkapfham** [comment]
Thanks to everyone for their feedback! @Michionlion I am leaning towards saying that every invocation of GatorGrader would require, say, the provision of the plugin directory or the specific plugin. Right now, my thought is that you could require the name of the plugin directory (or, perhaps even multiple plugin directories) and then the tool looks for the name of the specified check as a file in one of the plugin directories. Once it finds it, then it passes all command-line arguments to that plugin, which does the check and returns the result. 

As I think more about this feature, I'm thinking that I can see this approach being useful:

https://github.com/mitsuhiko/pluginbase

**Comment by gkapfham** [comment]
Hi, I wanted to let everyone know that I am actively working on this issue. I will create a WIP PR once I have a small prototype that is working and passing all of the test cases.
