### ISSUE TITLE
Run Tests with Multiple Versions of Python Using Tox on Local Machine

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#182]
**Is your feature request related to a problem? Please describe.**

There is no bug in the system in regards to this issue. At the outset, it is also important to note that the current setup for Travis CI supports the execution of the entire test suite in multiple versions of Python across the MacOS and Linux operating systems. We also currently run tests on Windows using AppVeyor. However, all of this happens in the cloud! It would be nice if we could run the test suite in all versions of Python that are available on a local development machine through Pyenv.

**Describe the solution you'd like**

Try to use tox to run the test suite in all local available versions of Python through pyenv.

**Describe alternatives you've considered**

Consider the need for packages that help Pyenv and Pipenv talk to tox. Are these needed?

**Comment by MaddyKapfhammer** [comment]
PR #185 resolves this issue.
