### ISSUE TITLE
Bring those stickers please ;)

### ISSUE THREAD

**Issue by corlettim** [GatorEducator/gatorgrader#193]
Professor Kapfhammer got some cool stickers at PyOhio and we would love to stick those all over our laptops

**Comment by gkapfham** [comment]
I brought stickers on Friday, but @alexheinle was away that day!

I will leave this issue open until everyone is confident that they have enough stickers. :grin:

@corlettim please close the issue as you deem appropriate!

**Comment by gkapfham** [comment]
I will bring more stickers to our meeting this week, @corlettim!
