### ISSUE TITLE
Improve the documentation to reference new features

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#194]
There are several new features of GatorGrader that are not documented in the README file:

- Use of Docker
- Plugin-based approach
- New sample repositories
- Description of the check for markdown components
- Description of the checks for different kind of counts
- References to other auto-grading tools (see my new internal list)
- Reference to article showing what happens when auto-graders crash (ask for reference)
- Correct use of the `ListChecks` option in the documentation in the "Running" section

Until all of these issues are addressed, the documentation for GatorGrader will be out of sync with the actual implementation of the tool!

**Comment by corlettim** [comment]
@Ktaylor2, once we get everything fully set up on your laptop, we would like for you to start on this issue! If you have any questions, please let us know. We are always more than welcome to help.
