### ISSUE TITLE
Preface the repository check with the word "The"

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#195]
The tool currently has the following check:

```
usage: CountCommits [-h] --count COUNT [--exact]
Check Provided by GatorGrader: CountCommits
optional arguments:
  -h, --help     show this help message and exit
required check arguments:
  --count COUNT  minimum number of git commits (default: None)
optional check arguments:
  --exact        equals instead of a minimum number (default: False)
```

When you run this check it produces a diagnostic that sayes "Repository contains ...".

While this is technically correct, it does not match the standard of the other checks, which all have the word "The" in front of the rest of the details. If you look at this example repo:

https://github.com/GatorEducator/java-assignment-starter-100-01

You can see an example of this issue by looking in the "Automated Checks with GatorGrader" section. Did you notice that the word "The" is missing for this check and needs to be added?

I think that we should add this missing word so that the checks are more uniform.

**Comment by Michionlion** [comment]
Has this fix been merged into master? If not, we should keep this issue open.

**Comment by corlettim** [comment]
@Michionlion  yes, we merged this into the master of the java solution...that is why we closed the issue.

**Comment by Michionlion** [comment]
@corlettim perhaps I'm misunderstanding things, but doesn't this need to be fixed in GatorGrader proper as well? [These lines](https://github.com/GatorEducator/gatorgrader/blob/master/gator/invoke.py#L35) in `invoke.py` suggest that the `The`-less output is still being produced.

**Comment by Michionlion** [comment]
Notably, this fix was made on a [forked PR](https://github.com/ajciancimino/gatorgrader/pull/1) that may have been incorrectly created.

**Comment by Michionlion** [comment]
Ah, and now #206 comes along to fix things!
