### ISSUE TITLE
Improve documentation in the Java solution repo

### ISSUE THREAD

**Issue by corlettim** [GatorEducator/gatorgrader#199]
There is minor change needed but small documentations must be fixed. Example: "Repository has 10 commits" and the word "the" needs to be added.

**Comment by schultzh** [comment]
How do we assign this issue to Kahlil ??

**Comment by schultzh** [comment]
Also, I believe this issue has been put in the issue tracker twice!

**Comment by corlettim** [comment]
@schultzh I messaged him asking for his GitHub user name and he still has not responded so until that happens, I am unsure. Also, I think the other documentation issue is for our specific README file but I could be wrong.
