### ISSUE TITLE
Move not-used repositories to a separate "incubator" organizations

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#201]
There are many repositories that are no longer used in this organization.

They should be moved to a new "incubator" organization like "GatorIncubator".

Tasks:

- Create the new organization
- Move the repositories to this new organization
- Ensure that continuing repositories in this organization do not reference those in the incubator organization unless there is a specific need to do so.

I am creating this issue here so that we can have a reminder of the need to complete this task.

**Comment by corlettim** [comment]
@sutterj Hannah, Alex, and I have made new repositories for the solution and starter repos. If you could please add the old repos into the GatorIncubator by next week, that would be great!! If you have any questions, please let us know!

**Comment by gkapfham** [comment]
Hi @sutterj can you please let us know if you are finished with this task? Once you are done, it would be great if you can mention the name of the organization here and then also give a reference to the URL for the organization. I don't think that we need to link to the repositories in any documentation, but it would be nice if this issue documented the name of the new organization and confirmed the movement of the repos before we close it. Okay, thanks!

**Comment by sutterj** [comment]
I believe that I have moved everything that should have been moved.  Let me know if I made a mistake.

The new organization is [GatorIncubator](https://github.com/GatorIncubator)
