### ISSUE TITLE
"gradle grade" hanging on certain Windows machines only in Docker

### ISSUE THREAD

**Issue by jjumadinova** [GatorEducator/gatorgrader#204]
*Note: this is a repeated issue post from: https://github.com/GatorEducator/gatorgradle/issues/59

When students run `gradle grade` on certain Windows machines, the checking is getting stuck (hanging and not completing checks) at the `ExecuteCommand --command "gradle build"` line in the "gatorgrader.yml" file. Without this line in the "gatorgrader.yml" file, the `gradle grade` command is able to complete. This happened in two instances so far (others did not encounter this issue on the same repository), both Windows machines (configs attached), running Gradle 5.6 and Python 3.6.

![windows_config1](https://user-images.githubusercontent.com/9140572/65722070-79c30780-e079-11e9-8014-d6e57a84e6f3.PNG) 
![windows_config2](https://user-images.githubusercontent.com/9140572/65722073-79c30780-e079-11e9-9856-a152488af58e.png)

**Comment by gkapfham** [comment]
Hi @jjumadinova, for now, let's keep the discussion in the other repository as we are not yet sure whether this is a problem for the Gradle plugin or for the GatorGrader system itself. Sounds okay?

**Comment by Michionlion** [comment]
Closing as not-our-issue (in this repository).
