### ISSUE TITLE
Add potential bug solution to README.md documentation.

### ISSUE THREAD

**Issue by schultzh** [GatorEducator/gatorgrader#216]
**Is your feature request related to a problem? Please describe.**

There are occasional instances when the `gradle grade` command is not recognized when run in the terminal. There is currently no way to automate detection of this issue as it could be caused by a multitude of factors depending on an individual's personal device and environment configuration.

**Describe the solution you'd like**

The solution for now is to document this issue and the manual steps to solve it in the documentation. The steps are: deleting the `virtualenvs` and `gatorgrader` folders from the `.local/share` directory. This allows the folders to be regenerated when creating the virtual environment. As far as we know, there is no harm in regenerating these folders.

**Additional context**

The only question I have regarding this documentation is whether the `.local/share` path is the same on both Mac/Windows/Liunx.

**Comment by Michionlion** [comment]
Just to verify, this is not `gradle grade` being unrecognized (which would be an issue with Gradle not being installed) but a command run by GatorGradle producing an error which is something like "command not recognized". Is that right?

**Comment by schultzh** [comment]
I've closed corresponding PR #217, so I will close this issue as well.
