### ISSUE TITLE
Transition to GitHub Actions

### ISSUE THREAD

**Issue by corlettim** [GatorEducator/gatorgrader#221]
This issue addresses the change from Travic CI to GitHub Action configurations.

In all currently labs and practicals that integrate GatorGrader have now started using GitHub Actions. Therefore, it would benefit gatorGrader to use this setup. Not only is it an easier configuration but GitHub Actions is faster.

We now no longer need appveyor and GitHub Actions will do all the work.

**Comment by schultzh** [comment]
[GitHub Actions Docs](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions)

[Migrating from Travis CI to GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions)

The first step in completing this task will be translating the `.travis.yml` file into GitHub Actions syntax, and identifying any process that will not directly translate.

**Comment by gkapfham** [comment]
Thanks for agreeing to work on this task @schultzh! Please let me and @corlettim know if you have questions about completing it. I look forward to having this new feature up and running as it will be incredibly useful. Some other notes to consider:

- At the start, we might want to keep Travis CI and AppVeyor along with GitHub Actions (especially as long as those builds are not breaking and there is no code to maintain or change).
- At some point, we probably want to deactivate the other build systems in favor of GitHub Actions. When?
- Finally, don't forget that we also need to figure out a way to translate the AppVeyor system setup to GitHub Actions as well.

**Comment by schultzh** [comment]
As I have been working on this issue, I no longer feel that GitHub Actions is developed enough for us to transition over. 

- MacOS and Ubuntu builds do not yet support the container actions needed to run the performance testing measures we currently use in Travis CI, such as: 
     - `pip`
     - `pipenv`
     - `mdl`

While those container actions are not necessary and manual commands can be used, they while not run across all OS systems either. This would make our `.yml` file over complicated, and ultimately lead to failing builds unrelated to our tool's status.

I do not think transitioning to GitHub Actions is a good idea at this time, but would still be a viable option in the future as it continues to develop to support more of our needs. Please let me know what you feel our next steps should be as I appreciate your feedback. @gkapfham @corlettim
