### ISSUE TITLE
Mysterious failing build for specific files in main and PRs

### ISSUE THREAD

**Issue by corlettim** [GatorEducator/gatorgrader#223]
This issue is to address the bug that we seem to be having with all PRs as well as the main branch.
This bug is breaking the build for Travis CI by saying that `black` is failing for the following files:
invoke.py
test_markdown.py
test_fragments.py

These build problems are happening specifically on Linux on Travis CI and some versions of Python on AppVeyor 

You can check the status of these failing builds by looking into the details of the main branch and all 6 PRs.

Black has been run on these files to test for any change in the issue but that did not help even though that is the stated problem in the build fail. 

Professor Kapfhammer plans to look into this when he has time and others are more than welcome to help as well!

**Comment by Michionlion** [comment]
This looks like it's an issue with different version of `black`: on some platforms, the default seems to be `19.10b0`, whereas on others it is `20.8b1`. These two versions treat a few select cases differently; for example, when running `black` on `gator/invoke.py` with the two different versions, the files end up with differences in two places:

```diff
732,735c732
<         (
<             met_or_exceeded_count,
<             actual_count,
<         ),
---
>         (met_or_exceeded_count, actual_count,),
801,804c798
<         (
<             met_or_exceeded_count,
<             actual_count,
<         ),
---
>         (met_or_exceeded_count, actual_count,),
```

Thus, I think we should pin the version of `black` in the Pipfile to one or the other (probably `19.10b0` just in case some platforms do not have the latest), and this issue should be resolved.
