### ISSUE TITLE
Do not use platform specific features in the test suite

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#61]
Currently the test suite uses the execution of commands like `ls`, which may not be available on a Windows computer. This means that the test suite is unlikely to pass when run like this:

```
pipenv run pytest -x -s --cov-config pytest.cov --cov-report term-missing --cov
```

on a windows machine that does not have a command like `ls` available for use. The test cases should be improved to be more platform independent while still testing functionality in an easy way. Perhaps a Python program could be written that also does an `ls`? Then, this could be called in the same way without breaking the functionality of the existing test cases.

**Comment by miller365** [comment]
The only test case that uses platform specific code is test_run.py. In this code there are two different test cases that I think are doing  the same test. Could you elaborate on the function of the test_run_command_grab_output_as_string function vs. test_run_working_command_returns_message function. @gkapfham

**Comment by gkapfham** [comment]
Hmm, @miller365, I'm going to have to review the code and get back to you later about the goals of those two test cases! Sorry for the further delay in reply! One thing that we should also be careful about is the use of path separators in the test suite &mdash; as I recall, there are test cases that only use path separators for Linux and thus those test cases will not work correctly on Windows.

Does @miller365 or @Michionlion know someone with a Windows machine who can test for us?

**Comment by karolvargas** [comment]
after testing on a windows and looking through the test classes. There are at least 6 files which are OS dependent due to path finding syntax specific to linux. This can be resolved using the pathlib library in python but this would call for a major refactor of the code as well as further research into what out of the main directory (gator) also uses OS specific path finding to linux.

**Comment by gkapfham** [comment]
Thanks for this update @karolvargas. If you have time and you are interested, we would love to have you submit a PR to resolve this issue. If not, then we of course understand and would appreciate it if you could point someone else to this issue. Thanks again for your diagnosis of the problem!
