### ISSUE TITLE
Update the README to list both/all current sample labs

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#63]
The current version of the README points to the single sample laboratory repository. However, this has now been divided into two sample labs, one for a "starter" repository that would be given to students and one for a solution repository for a professor. Both of these links should be included. Once more of these sample repositories are available, then there should be a separate section in the README file for all of these.

**Comment by ohnoanarrow** [comment]
Could you clarify which repository links you're referring to? The closest I found to what you're describing are four links at the bottom of the README which lead to Github Classroom pages. These pages contain repositories which contain all of the course's labs, but no solutions. Thank you!

**Comment by Michionlion** [comment]
#101 duplicates this issue.
