### ISSUE TITLE
Document new strategies for running the test suite

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#69]
The README currently documents a few of the representative ways in which you can run GatorGrader's test suite. However, it is a good idea for us to include additional commands and then explain what they do. For instance, when debugging GatorGrader, it is a good idea for a developer to first run (or, exclusively run) the test case that previously failed. Since Pytest has features that support all of these types of test execution strategies, they should be documented in the README file.

**Comment by karolvargas** [comment]
Updated README.md with documentation on how to run pytest for a specific test that failed as well as how to run other pytest commands

**Comment by Michionlion** [comment]
@karolvargas, what #PR was that was that merged in? It can be useful to link to the work here; then this issue can be closed.

**Comment by karolvargas** [comment]
I apologize I had forgot to link it @Michionlion . It is #129

**Comment by gkapfham** [comment]
Hello @Michionlion and @karolvargas, I am going to close this issue as I think that the PR has solved it appropriately. Please reopen if you think that there are other issues that we still need to handle!
