### ISSUE TITLE
Create a repository containing a sample assignment written in Python

### ISSUE THREAD

**Issue by jjumadinova** [GatorEducator/gatorgrader#70]
Could we have a sample repo created that uses GatorGrader to check Python programs and not Java? Is PyGradle recommended for GatorGrader use?

**Comment by Michionlion** [comment]
I've started this in the [python-starter](https://github.com/GatorEducator/python-starter) repo. What exactly are the ideas for requirements? PyGradle is very complex and uses `setuptools` along with a lot of dependency management plugins. It may be simpler to use a smaller plugin that simply provides the tasks to run python programs, depending on what you have in mind.

**Comment by Michionlion** [comment]
I've finished a basic sample using the `use-python` plugin, which is considerably simpler than PyGradle and does similar things. Any further discussion on requirements, etc, should be held in the [python-starter](https://github.com/GatorEducator/python-starter) issue tracker.

**Comment by gkapfham** [comment]
Hi @Michionlion, thanks for creating this new sample repository. I know that you have already created a new repository and closed this issue. However, I thought it would be useful to put a few follow-on points here:

- @jjumadinova, can you tell us which features you would like the repository to demonstrate?
- @Michionlion, can you explain a little about the `use-python` plugin?
- @Michionlion, can you make a TODO list in that new start repository with the issue tracker?

Perhaps there is a way for some students to take on the extension of this start repository as a Hacktoberfest project?

**Comment by Michionlion** [comment]
I'll use this space to explain about `use-python`, I've also created issues for the relevant TODO items in the [python-starter](https://github.com/GatorEducator/python-starter) issue tracker.

So, `use-python` provides two basic pieces of functionality: first, it provides an interface to an external version of python (installed globally, through `pyenv`, or just at some path) that unifies task creation. This means that you can easily create a `run` task that simply passes the name of the script to run to the python executable (easily seen [here](https://github.com/GatorEducator/python-starter/blob/master/build.gradle#L35)). Secondly, `use-python` integrates `pip` and `virtualenv` to automatically create a virtual environment for use by the project, with all the specified dependencies installed. This means it is very straightforward to create basic python projects that would normally just use `pip` and be run with `some/python/executable <name>`. There's excellent, straightforward documentation in the github [repo](https://github.com/xvik/gradle-use-python-plugin) as well.
