### ISSUE TITLE
Fix the paragraph checks that don't disregard markdown syntax

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#73]
It seems as though a Markdown list will be counted as a paragraph when it should not be. This means that paragraph checks for a specific number of words will not pass because they are considering the Markdown list, or perhaps part of it, as a paragraph and noticing that it does not have the required number of works. This is connected to Issue #45 which requests new test cases for this same block of code.

**Comment by gkapfham** [comment]
It is also important to note that this check might require the use of a full-fledged Markdown parser.

**Comment by Michionlion** [comment]
As this issue will be solved by the implementation of #81, I am closing it. If in the future we need alternate solutions, feel free to reopen this issue!

**Comment by gkapfham** [comment]
Hi, @Michionlion, I agree that it is fine for us to close this issue. I'm looking forward to a full implementation that resolves #81!
