### ISSUE TITLE
Fix the broken link to a sample lab in the README file

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#74]
There is a link at the very end of the README file that still references the old GitHub repository for the sample laboratory assignment. In line with Issue #63 and #64, this link should probably be deleted. Overall, this site should maintain a curated list of all of the sample repositories.

**Comment by Michionlion** [comment]
A new issue would be the best I think!

**Comment by gkapfham** [comment]
Done @Michionlion, there is now #101 for this. I will work on this task with other collaborators.
