### ISSUE TITLE
Create new sample repository for LaTeX documents

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#75]
While we currently have several sample repositories available, those probably need to be updated to illustrate the wide variety of checks that are now available. Also, we need to create a new sample repository that includes checks for LaTeX source code. For instance, we should consider having checks for algorithms, equations, technical writing references, and bibliographies. In some cases, this might require us to add new types of checks to GatorGrader. In other cases, it should be possible to use the existing checks but with very different fragments.

**Comment by everitt-andrew** [comment]
An issue that we've created in our individual repository mentions that we will most likely need to implement new, more in-depth checks for LaTeX code. These checks would focus on whole expressions such as the necessary code in order to implement an element such as an enumerated list.

**Comment by leonardoz15** [comment]
We've also discussed implementing a linter for LaTeX files in order to keep all styling uniform outside what the default LaTex checker produces. I raised this as an issue [#3](https://github.com/GatorEducator/latex-assignment-starter/issues/3).

**Comment by gkapfham** [comment]
Hi @everitt-andrew, there is now #102. Thanks for pointing out this issue. I think that we should aim to soon implement this feature!

**Comment by everitt-andrew** [comment]
We have completed the LaTeX sample repository with basic checks for single line fragments. We are now moving on to [Issue 102](https://github.com/GatorEducator/gatorgrader/issues/102) which focuses on capturing regular expressions.

**Comment by everitt-andrew** [comment]
We have completed the LaTeX sample repository with basic checks for single line fragments. We are now moving on to [Issue 102](https://github.com/GatorEducator/gatorgrader/issues/102) which focuses on capturing regular expressions.
