### ISSUE TITLE
Add check for multiple-line Python docstring comments

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#83]
Although it is possible to have multiple-line comments in Python in the form of docstrings that are part of, say, a function's description, the GatorGrader tool does not have a check for these. We should add this feature to the tool so that it is possible to ensure that a Python program has an adequate number of docstrings. We would need to either add a regular expression for docstrings or perhaps use the Python parser and then extract. At this point, we would need to ensure that the number of docstrings matches the specification for the check. The implementation of this feature will also require the support of Python as a language for the multiple-line check.

**Comment by miller365** [comment]
From some preliminary research I believe that using regular expressions to implement this feature would take some work. We could use pythons Abstract Syntax Tree(ast). To retrieve all of the doc-strings from python functions and classes, much more systematically. I am working on a mock up now. Here is the description of the module here:[https://docs.python.org/3.4/library/ast.html](url)

**Comment by Michionlion** [comment]
Just as a note, @cs481-team4 is also working on this issue, headed up by @mendezjw.

**Comment by gkapfham** [comment]
Hi @miller365 and @mendezjw and @Michionlion, thanks for looking into this issue. Once you learn more, please report back here so that we can have an effective strategy for moving forward with a complete and well-tested implementation. I think that this is an important feature to add as Python is one of the main languages that we support and right now we do not have an easy way to check for their presence and count them.

**Comment by gkapfham** [comment]
Also, @Michionlion, is there a benefit to having the discussion in the other location?

**Comment by Michionlion** [comment]
Not really, @gkapfham. @miller365 can you add your post there to this issues?
