### ISSUE TITLE
Run tests on multiple Python versions and operating systems

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#87]
It would be really useful if we always ran this project's test suite in multiple versions of Python when testing in Travis CI. It seems like it might be possible to achieve this by using some combination of Pyenv and Tox. Can someone with expertise on these two systems investigate and determine the feasibility? Overall, I would like to have more confidence that GatorGrader will work in a wide variety of execution environments.

**Comment by mendezjw** [comment]
After some initial research, I think that the Travis CI documentation solves the need for testing multiple python versions and different operating systems through the use of a matrix. Do we know which python versions we are looking to test besides python version 3.6? I have included the link for reference.
https://docs.travis-ci.com/user/multi-os/

**Comment by Michionlion** [comment]
I'm actually working on this and have a nearly complete and working setup on the `feature/travis-ci-multiple-jobs` branch.

**Comment by Michionlion** [comment]
This was merged in PR #121.
