### ISSUE TITLE
Update the instructions for installing Python and Pipenv?

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#88]
My recent experiences suggest that potential contributors may struggle with installing a modern version of Python in their development environment and then additionally installing Pipenv. Without both of these systems already installed, you cannot installed GatorGrader's development dependencies and then run the test suite and add new features. While I am concerned about adding too much to the README file, I suggest that we add a little bit of additional content. What do others think?

**Comment by miller365** [comment]
I think that this addition would be excellent. Would you like these instructions for all OS?

**Comment by gkapfham** [comment]
Yes, if possible, I think that the instructions should support Windows, MacOS, and LInux. @miller365, do you think that it would be possible to write these instructions in a concise way while still ensuring that a person using one of these operating systems can get the steps to work? My view is that using Pyenv would make it easier for people using MacOS and LInux &mdash; I'm not sure, has anyone recently tried Pyenv on Windows?
