### ISSUE TITLE
Add a dependency section of the README

### ISSUE THREAD

**Issue by miller365** [GatorEducator/gatorgrader#89]
I believe that there needs to be a dependency section clearly outlined in the README file so people know what software they need installed on their computer to use Gator Grader. Maybe a section that combines the installation and statement of these dependencies.

**Comment by gkapfham** [comment]
Hi @miller365, thanks for bringing this issue to our attention! Our goal is to use Pipenv to manage all of the development and application dependencies. So, whatever is currently listed in the `Pipfile` should represent what Pipenv will install for you to do development correctly. With that said, I think that it might be a good idea to include a statement near the end of the README file that mentions some/all of the development dependencies. For instance, as I mentioned in #92 we are using Black to perform code formatting. While this tool will be installed by Pipenv, many people may not be using the tool yet so it might be cool to include a link to it and some of the other tools (e.g., Flake8 and Pylint). How do we pick the right tools to include in the list, @miller365 and @Michionlion?

**Comment by gkapfham** [comment]
This issue is resolved by PR #181.
