### ISSUE TITLE
Document style checking in the README

### ISSUE THREAD

**Issue by miller365** [GatorEducator/gatorgrader#92]
There should be some information about styling guides for contribution purposes. You will fail the CI test if you haven't adhered to the flake8 tests.

**Comment by gkapfham** [comment]
Thanks for raising this issue @miller365, I agree that it is important that we document the style guide to which we adhere in the README file. I suggest that this documentation point out that we are also adopting the Black code formatting tool to make it easy to keep source code in alignment with the style guide. If you are interested in working on this task, please let us know here. You are welcome to start the work and create a PR and then tag @gkapfham and @Michionlion as reviewers. We would be glad to work with you to ensure that PR can be merged into the master branch!

**Comment by gkapfham** [comment]
This issue is resolved by PR #181.
