### ISSUE TITLE
Add a logo and a project summary

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#96]
This project needs to have a logo and a catchy project summary at the start of the README! The logo should be designed in SVG format. Here are some resources:

http://logodust.com/

http://openlogos.org/

Please note that the first site has logos that we can download and try to incorporate. The second page only has logos that we can use for inspiration as they have already been claimed. Once we have a great logo, I would like to start making stickers that we can share with developers!

**Comment by dubswalker** [comment]
I'm drawing a logo from scratch. Should I use the exact same font theme and colours from the college's logo [graphic standards](https://sites.allegheny.edu/collegerelations/graphic-standards/)? 

Would we have to worry about any copyright from the school or anything of that nature? Or should I use a different but similar colour theme

**Comment by baldeosinghm** [comment]
I'll continue work on the logo's project summary in the README.
