### ISSUE TITLE
Add new sample repositories for many projects

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#97]
The are many types of sample assignment repositories that we do not have yet! While #64 mentions that we need to create a sample repository for LaTeX, it would also be great if we had sample repositories for the following programming languages:

* C and/or C++
* Markdown
* Markdown with images, links, etc.
* HTML with CSS
* HTML with CSS and JavaScript
* R for data science
* Python for data science
* Python for discrete structures

To best ensure the adoption of GatorGrader, we really need to have samples for all of these! Who can help with this high-impact task?

**Comment by Alex-Yarkosky** [comment]
Update on where this issue currently stands, it seems that there are currently four of these already included as repositories within the organization. Those being, [Java](https://github.com/GatorEducator/java-assigment-starter), [LaTeX](https://github.com/GatorEducator/latex-assignment-starter), [HTML with CSS](https://github.com/GatorEducator/HTML-CSS-assignment-starter), and [Python](https://github.com/GatorEducator/python-assignment-starter). I can't tell if the Python one is for data science or discrete structures. It also seems that updates need to be made to the documentation for the HTML with CSS one as well as the Python one.

**Comment by lylet-AC** [comment]
I believe that the current Python repository is for a general Python submission, and thus, different repositories for specific focuses are still necessary.

**Comment by lylet-AC** [comment]
I also agree with @miller365.  I am attempting to set up gatorgrader on one of my existing repositories for discrete structures and I have on clue where to begin.  Additional documentation seems entirely necessary as a precursor for this issue.

**Comment by Alex-Yarkosky** [comment]
For who will be handling what, @shafferz will take on C and/or C++, Markdown, & Markdown with images, links, etc., @Alex-Yarkosky will take on HTML with CSS & HTML with CSS and Javascript, & @lylet-AC will take on R for data science, Python for data science, & Python for discrete structures.

**Comment by Alex-Yarkosky** [comment]
@lylet-AC @shafferz one check that we should always have is to make sure that there are exactly 0 TODOs in all applicable files after speaking @gkapfham in person about this issue more.
Additionally, I will keep in mind to check the fragments, and the existence of a screenshot for the HTML examples.

**Comment by Michionlion** [comment]
@lylet-AC You should have a good reason to split Python samples into two labs -- is there a real reason for that?

**Comment by gkapfham** [comment]
Hi, I should be able to resolve this issue by the end of the summer, ensuring that there are samples for all relevant assignments that adhere to the tool's new "linter interface", as described in Issue #175.

It is also worth noting that you can now configure a repository to be a template:

https://help.github.com/en/articles/creating-a-template-repository
