### ISSUE TITLE
Add a license file for the project

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#99]
Hello @Michionlion and @jjumadinova and @yeeunmariakim and @miller365, we currently do not have a license for the GatorGrader project. I'm aware of the some of the trade-offs of different open-source licenses and, for some of my recent projects, my colleagues and I have picked the MIT License. Do any of you have a preference for which license we select for this project? We should think carefully about this issue and add a license file in a follow-on release of this tool!

**Comment by miller365** [comment]
I believe that either the MIT License or the GNU General Public License would be good choices for this project. Although I have very limited familiarity with licensing software.

**Comment by yeeunmariakim** [comment]
As I do not have much familiarity with open-source licenses, I have no strong preference and will gladly defer to the opinions of those who are more knowledgeable :)

**Comment by Michionlion** [comment]
I generally like the GNU license, since it requires any new forks or other offshoots to also share their source.
